#!/bin/bash

# Quick fix script for VPS deployment
echo "Fixing deployment issues on VPS..."
echo ""
echo "Run these commands on your VPS:"
echo ""
echo "cd /home/docgen/backend"
echo ""
echo "# Pull latest fixes"
echo "cd rapiddocs && git pull origin master && cd .."
echo ""
echo "# Copy updated files"
echo "cp -r rapiddocs/backend/* ."
echo ""
echo "# Rebuild and restart"
echo "docker-compose down"
echo "docker-compose build --no-cache"
echo "docker-compose up -d"
echo ""
echo "# Check logs for initial key"
echo "docker-compose logs | grep -A 5 'INITIAL SETUP'"
echo ""
echo "# Test health"
echo "sleep 10"
echo "curl http://localhost:8000/health"