#!/bin/bash

# Quick update script for VPS deployment after fixes
echo "==============================================="
echo "RapidDocs Backend - VPS Update Script"
echo "==============================================="
echo ""
echo "This script will update your VPS with the latest fixes."
echo "Run these commands on your VPS as root or docgen user:"
echo ""
echo "# 1. Navigate to backend directory"
echo "cd /home/docgen/backend"
echo ""
echo "# 2. Pull latest fixes from GitHub"
echo "cd rapiddocs && git pull origin master && cd .."
echo ""
echo "# 3. Copy updated files to deployment directory"
echo "cp -r rapiddocs/backend/app/* app/"
echo "cp rapiddocs/backend/Dockerfile ."
echo "cp rapiddocs/backend/docker-compose.yml ."
echo ""
echo "# 4. Stop and remove current container"
echo "docker-compose down"
echo ""
echo "# 5. Rebuild with the fixes (no cache to ensure fresh build)"
echo "docker-compose build --no-cache"
echo ""
echo "# 6. Start the updated container"
echo "docker-compose up -d"
echo ""
echo "# 7. Check logs to verify the fix worked"
echo "sleep 5"
echo "docker-compose logs --tail=50"
echo ""
echo "# 8. Check container health"
echo "docker ps"
echo ""
echo "# 9. Test the health endpoint"
echo "curl -I http://localhost:8000/health"
echo ""
echo "# 10. Look for the initial referral key (if first run)"
echo "docker-compose logs | grep -A 2 'INITIAL SETUP'"
echo ""
echo "==============================================="
echo "After running these commands:"
echo "1. The duplicate key error should be resolved"
echo "2. Container should show as 'healthy'"
echo "3. Visit https://api.rapiddocs.io to see login page"
echo "4. Use the referral key from logs to register first admin"
echo "==============================================="